# -*- coding: utf-8 -*-
"""task-3 server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHY1fMBWYFtnw5FxB_2YCXIAY3FvRz8L
"""

import socket
import threading

def count_vowels(message):
    vowels = 'aeiouAEIOU'
    return sum(1 for char in message if char in vowels)

def handle_client(client_socket, client_address):
    print(f"Connection established with {client_address}")

    try:
        data = client_socket.recv(1024).decode('utf-8')
        print(f"Received message from {client_address}: {data}")

        vowel_count = count_vowels(data)
        if vowel_count == 0:
            response = "Not enough vowels"
        elif vowel_count <= 2:
            response = "Enough vowels I guess"
        else:
            response = "Too many vowels"

        client_socket.send(response.encode('utf-8'))
        print(f"Response sent to {client_address}: {response}")
    except Exception as e:
        print(f"Error handling client {client_address}: {e}")
    finally:
        client_socket.close()

def start_server():
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_address = ('0.0.0.0', 12345)
    server_socket.bind(server_address)
    server_socket.listen(5)

    print("Multi-threaded server is running and waiting for connections...")

    while True:
        client_socket, client_address = server_socket.accept()
        client_thread = threading.Thread(target=handle_client, args=(client_socket, client_address))
        client_thread.start()

if __name__ == "__main__":
    start_server()