# -*- coding: utf-8 -*-
"""task-4 client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHY1fMBWYFtnw5FxB_2YCXIAY3FvRz8L
"""

import socket

def calculate_salary(hours_worked):
    if hours_worked <= 40:
        return hours_worked * 200
    else:
        overtime_hours = hours_worked - 40
        return 8000 + (overtime_hours * 300)

def start_server():
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_address = ('0.0.0.0', 12345)
    server_socket.bind(server_address)
    server_socket.listen(5)

    print("Server is running and waiting for connections...")

    while True:
        client_socket, client_address = server_socket.accept()
        print(f"Connection established with {client_address}")

        try:
            data = client_socket.recv(1024).decode('utf-8')
            hours_worked = int(data)
            print(f"Hours worked received from client: {hours_worked}")

            salary = calculate_salary(hours_worked)
            response = f"The salary is Tk {salary}"
            client_socket.send(response.encode('utf-8'))
            print(f"Salary sent to client: {response}")

        except ValueError:
            client_socket.send("Invalid input. Please send a valid number of hours.".encode('utf-8'))
        except Exception as e:
            print(f"Error handling client {client_address}: {e}")
        finally:
            client_socket.close()

if __name__ == "__main__":
    start_server()