# -*- coding: utf-8 -*-
"""task-1 client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHY1fMBWYFtnw5FxB_2YCXIAY3FvRz8L
"""

import socket
import platform

def connect_to_server():
    server_address = ('127.0.0.1', 12345)  # Server IP and port
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    try:
        client_socket.connect(server_address)
        device_name = platform.node()  # Get the device name
        client_ip = socket.gethostbyname(socket.gethostname())  # Get the client IP
        message = f"Device Name: {device_name}, IP: {client_ip}"

        client_socket.send(message.encode('utf-8'))
        print("Information sent to the server.")

    except Exception as e:
        print(f"Error: {e}")
    finally:
        client_socket.close()

if __name__ == "__main__":
    connect_to_server()